# docker-compose.yml
version: '3'
services:
    db: 
        image: postgres:11-alpine
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: api_dev
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
        ports: 
            - '5432:5432'
    api:
        environment: 
            MIX_ENV: dev
        build: ./api/
        ports:
            - "4000:4000"
        depends_on:
            - db
    webapp:
        build: ./webapp/
        ports: 
            - "8080:8080"    
        depends_on: 
            - api

volumes:
    postgres_data:
    